[package]
name = "with_lock"
version = "0.1.0"
edition = "2021"
description = "Prevent deadlocks"
documentation = "https://docs.rs/with_lock"
readme = "README.md"
repository = "https://github.com/Milo123459/with_lock"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
